### ISSUE TITLE
sudo adduser  not found

### ISSUE THREAD

**Issue by bakman2** [RaymondMouthaan/node-red-homekit-docker#10]
Synology does not have the `adduser` command. 
Is there an option to specify a local account like the node-red-docker container or another way to specify the UID ?

**Comment by RaymondMouthaan** [comment]
Sorry for the late response, totally missed this issue.

For Synology, you could start the container from commandline with the --user <uid>:<gui> option. Unfortunately this can't be set from DSM webinterface.
Check [here](https://docs.docker.com/engine/reference/run/) for more info.

Hope this fixes your issue.
