### ISSUE TITLE
[REQUEST] Docker Image Testers

### ISSUE THREAD

**Issue by RaymondMouthaan** [RaymondMouthaan/node-red-homekit-docker#21]
Hi all,

Because Node-RED v1.0.x and node-red-contrib-homekit-bridged v0.7.1 are released, I've created a new set Docker images.

Under the hood these images have a different approach then before, so before I release a final version, I like to **request for testing**. 

If you have questions or issues, please raise them [here](https://github.com/RaymondMouthaan/node-red-homekit-docker/issues).

The images can be found here: [node-red-homekit-dev](https://cloud.docker.com/repository/docker/raymondmm/node-red-homekit-dev/tags) and they are available for `arm32v6`, `arm32v7`, `arm64v8` and `amd64`.

The images are available in different variants, for more details see [Image-Variations-and-Manifest-Lists](https://github.com/node-red/node-red-docker/wiki/Image-Variations-and-Manifest-Lists).

__note: currently there are no manifest list available - use the image tag__

### Quick start

```
docker run it --net=host -v <path_on_host>:/data --name=homekit raymondmm/node-red-homekit-dev:<tag>
```

### Synology Users

```
docker run it --net=host -v <path_on_host>:/data -e DSM_HOSTNAME=<synology_hostname> --name=homekit raymondmm/node-red-homekit-dev:<tag>
```

### Permissions

Since Node-RED 1.0 the container user is `node-red` and has uid `1000` and gid `1000`, make sure your <path_on_host> has the same uid and gid:

Verify command:
```
ls -nal <path_on_host>
```

Modify command:
```
chown -R  1000:1000 <path_on_host>
```

Please let me know, which images you tested.

Regards,
Raymond

**Comment by micha149** [comment]
🤔Hmm… my bridge isn't advertised on homekit with the new image. I am using `raymondmm/node-red-homekit-dev:beta.1-1.0.1-10-minimal-amd64` on a Synology DS 918+. 'DSM_HOSTNAME' is set to the same value as `HOSTNAME` had in the old image.

**Comment by micha149** [comment]
Hmm.. Seems to be caused by my mounted volume wich contains my old flows etc. I started a container without any volume and I was able to create a service and see my bridge in Homekit.

**Comment by stoinov** [comment]
**beta.1-1.0.1-12-minimal-arm64v8** seems to work fine for me.

I also tried a new deploy from scratch and imported the flows - only Random node was missing.

**Comment by RaymondMouthaan** [comment]
@micha149, did you solve it on your DS 918+?

@stoinov, yes Random node was pre installed earlier, but since NR 1.0.0 I've removed it to be inline with the Node-RED docker images. Actually these images have the official Node-RED images as base, while earlier versions did not.

**Comment by stoinov** [comment]
Saw your new builds - deployed anew using **latest-12-minimal**. Works as expected :)
I see that 12 will [become LTS tomorrow](https://nodejs.org/en/about/releases/), so I could probably switch to just latest-minimal soon 😄

**Comment by RaymondMouthaan** [comment]
@stoinov, glad it works :) Soon I'll release a new set to `raymondmm/node-red-homekit`
Node 10 remains the default, as longs as it is the default for Node-RED, but feel free to use the `12` tag for Node 12 :-)

**Comment by RaymondMouthaan** [comment]
Just release 2.0.0 here [node-red-homekit](https://hub.docker.com/r/raymondmm/node-red-homekit/tags?page=1&ordering=last_updated).

I'll close this issue now, but feel free to create a new one if you have issues / questions :-)
