### ISSUE TITLE
Env for node-red port

### ISSUE THREAD

**Issue by maragelis** [RaymondMouthaan/node-red-homekit-docker#28]
Is there a way you could expose the node-red port so it can be changed. This will help if we need to run two instances on the same computer.

**Comment by maragelis** [comment]
Found away, using the settings file for node red.

**Comment by Shaquu** [comment]
@maragelis so the issue can be closed?

**Comment by RaymondMouthaan** [comment]
Sorry for the late response, totally missed this issue.

This image only works when running on the host network, so exposing ports isn't applicable. To change the Node-RED port, you change it through the `settings.js`:

```
    // the tcp port that the Node-RED web server is listening on
    uiPort: process.env.PORT || 1880,
```
