### ISSUE TITLE
Add tzdata in build

### ISSUE THREAD

**Issue by roswennen** [RaymondMouthaan/node-red-homekit-docker#3]
Raymond, great image but I have 1 issue it's the Time zone.  This is an Alpine issue, TZ cannot be set but there is a solution to add tzdata so Timezone can be set as ENV variable.
see https://github.com/gliderlabs/docker-alpine/issues/136

So can you please rebuild the image including the tzdata?

Kind regards and all kudos for the great work.

**Comment by RaymondMouthaan** [comment]
@roswennen apologise for my late response, totally missed your issue .. very busy with house movement. As soon as i have time I will look in to this :-)

**Comment by RaymondMouthaan** [comment]
Would it be oke for you to use the following command?

```docker run -d --network host -e HOST_NAME=$HOSTNAME --name my-node-red -v /volume1/docker/node-red-homekit:/data -v /etc/localtime:/etc/localtime:ro -v /etc/TZ:/etc/TZ:ro raymondmm/node-red-homekit```

**-v /etc/localtime:/etc/localtime:ro -v /etc/TZ:/etc/TZ:ro** maps localtime and TZ file from the host os to the docker container and works here.

**Comment by roswennen** [comment]
Let me check, I'm using Synology GUI version of docker so need to figure out how to do this in the Synology app but will report back

**Comment by RaymondMouthaan** [comment]
You could login on your synology with ssh, then execute the docker command as sudo. This is the way I run docker containers on my synology. The gui provided by synology to run docker containers is limited.

**Comment by roswennen** [comment]
ok, will try that tonight.  This will run your container as root? So if something goes wrong it can mess up your entire NAS core files ?  Isn't the whole ID of docker running as a separate user to protect your system?

**Comment by RaymondMouthaan** [comment]
All your containers run like this, since docker runs like that 😉

**Comment by roswennen** [comment]
Thanks, that really worked.  Customized my folders but other than that it did work as you described and can indeed start and stop container from GUI.  Thanks a lot !!

**Comment by RaymondMouthaan** [comment]
Great I could help! 😀
