### ISSUE TITLE
ffmpeg fails to play rtsp

### ISSUE THREAD

**Issue by stoinov** [RaymondMouthaan/node-red-homekit-docker#37]
### What are the steps to reproduce?
I am deploying the `latest-12-minimal` image on my Odroid C2 and adding camera accessory with reolink rtsp.

### What happens?
Initially after adding the camera accessory, the stream works, but after any redeploy of Node or restart of the container, the stream times out and I get `ERROR: FFmpeg exited with code 1` in the container logs. At some point during the testing, even this stopped working and now I cannot make the stream works at all.
The same problem happens with a clean install on RPi Zero with the latest OS and updates.

### What do you expect to happen?
Proper video stream.

### What is the suggested fix?
When I execute this in the container or on the Pi with the proper architecture, the stream starts working without doing anything else:
`curl -Lf# https://github.com/homebridge/ffmpeg-for-homebridge/releases/download/v0.0.6/ffmpeg-alpine-aarch64.tar.gz | tar xzf - -C / --no-same-owner`
so along with using the OS provided ffmpeg package, can we also add the [ffmpeg for homebridge](https://github.com/homebridge/ffmpeg-for-homebridge) version? It seems you're already using something similar for s6-overlay.

### Please tell us about your environment:
- [X] Node-RED version: 1.1.1
- [X] node.js version: 12.14.0
- [X] npm version: 6.13.4
- [X] Platform/OS: arm64/Docker image
- [X] Browser: Chrome

**Comment by RaymondMouthaan** [comment]
@stoinov, 

Does `ffmpeg for homebridge` replaces the pre-installed `fmpeg` ? if it does I can remove it and use `ffmpeg for homebridge` instead.

I no longer use this image, so I can not test it. If your are willing to test the new image once it has been build, that would be great.

**Comment by stoinov** [comment]
I don't think it replace it, but rather takes precedence for the execution in Node. My guess is based on the fact that the output of `ffmpeg` in the container console did not change after the install.

I am ok with testing any changes but as for removing the apk install - it might break unintentionally some other use cases.

We can try and see what will happen tho.

**Comment by RaymondMouthaan** [comment]
Okay, sounds like a good plan. I'll add it and let you know when the images are available for testing 👌🏼

**Comment by RaymondMouthaan** [comment]
@stoinov, as far I could see, `ffmpeg for homebridge` replaces the pre-installed `ffmpeg` package. Therefore I builded new test images without it and with `ffmpeg for homebridge` as a replacement. You can find the images [here](https://hub.docker.com/repository/docker/raymondmm/node-red-homekit-dev/tags?page=1). Would you like to test them and let me know if it works as expected?

**Comment by stoinov** [comment]
Sorry for the delay - computer reorganization at home :D
The new 12-minimal image works well.

I've also confirmed that the `ffmpeg` versions differ:
- 4.1.5 built with gcc 8.3.0 for the old one
- 4.2.2-d1e8be3 built with gcc 9.2.0 for the new one

**Comment by RaymondMouthaan** [comment]
No problem for the delay. Hope your computer is nicely reorganized.

Thanks for testing and getting back with good results. I'll merge the branch to master and build new images with ffmpeg-homebridge shortly.

**Comment by RaymondMouthaan** [comment]
The new images are available at [raymondmm/node-red-homekit](https://hub.docker.com/repository/docker/raymondmm/node-red-homekit).

I'll close this issue, but feel free to re-open in case of issues. Thanks for your contribution @stoinov 👍
